#define GRAVE_ESC_GUI_OVERRIDE    # Always send Escape if GUI is pressed
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define BACKLIGHT_BREATHING
#define BREATHING_PERIOD 6

